apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: backstage

resources:
  - argocd/application.yaml

# Patches para diferentes ambientes
patchesStrategicMerge: []

# Configurações de ambiente
namespace: backstage

# Labels comuns
commonLabels:
  app: backstage
  managed-by: argocd

# Annotations comuns
commonAnnotations:
  deployed-by: github-actions