{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-backstage-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.postgres.username }}
  POSTGRES_DB: {{ .Values.secrets.postgres.database }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password }}
{{- end }}