apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backstage.service.type }}
  ports:
    - port: {{ .Values.backstage.service.port }}
      targetPort: {{ .Values.backstage.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "backstage.selectorLabels" . | nindent 4 }}