{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "backstage.fullname" . }}-route
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ include "backstage.fullname" . }}-gateway
      namespace: {{ .Values.namespace }}
  hostnames:
    - "{{ .Values.gateway.hostname }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "backstage.fullname" . }}-service
          port: {{ .Values.backstage.service.port }}
{{- end }}