apiVersion: v1
kind: Namespace
metadata:
  name: backstage

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-backstage-secret
  namespace: backstage
type: Opaque
data:
  POSTGRES_USER: YmFja3N0YWdlX3VzZXI=
  POSTGRES_DB: YmFja3N0YWdlX2Ri
  POSTGRES_PASSWORD: cGFzc3dvcmQ=