name: Backstage CI-CD Ultra-Paralelo Optimizado

permissions:
  contents: read
  security-events: write

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'packages/backend/**'
      - 'packages/app/**'
      - 'helm-chart/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'packages/backend/**'
      - 'packages/app/**'
      - 'helm-chart/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Escolha o ambiente para deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.12.0'
      - name: Lint Helm Chart
        run: helm lint helm-chart/
      - name: Validate Helm Templates
        run: helm template backstage helm-chart/ --debug --dry-run

  security-scan:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'helm-chart/'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  build-app:
    name: Build & Push Apps (Backend + Frontend)
    runs-on: ubuntu-latest
    needs: [lint, security-scan]
    strategy:
      matrix:
        app: [backend, frontend]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Set working directory
        id: set-dir
        run: |
          if [ "${{ matrix.app }}" == "backend" ]; then
            echo "DIR=packages/backend" >> $GITHUB_OUTPUT
          else
            echo "DIR=packages/app" >> $GITHUB_OUTPUT
          fi

      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/yarn
            ~/.yarn
          key: yarn-cache-${{ matrix.app }}-${{ hashFiles('packages/' + matrix.app + '/yarn.lock') }}

      - name: Install dependencies and build
        run: |
          cd ${{ steps.set-dir.outputs.DIR }}
          yarn install --immutable
          if [ "${{ matrix.app }}" == "backend" ]; then
            yarn build
          else
            yarn build
          fi

      - id: set-tag
        run: |
          IMAGE_TAG="v$(echo $GITHUB_SHA | cut -c1-7)"
          echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ steps.set-dir.outputs.DIR }}
          file: ${{ steps.set-dir.outputs.DIR }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backstage-${{ matrix.app }}:${{ steps.set-tag.outputs.tag }}

  update-helm-values:
    name: Update Helm Chart Values
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - uses: actions/checkout@v4
      - name: Update values.yaml
        run: |
          BACKEND_TAG=$(jq -r '.[] | select(.matrix.app=="backend") | .steps[] | select(.id=="set-tag") | .outputs.tag' <<< '${{ toJSON(needs.build-app) }}')
          FRONTEND_TAG=$(jq -r '.[] | select(.matrix.app=="frontend") | .steps[] | select(.id=="set-tag") | .outputs.tag' <<< '${{ toJSON(needs.build-app) }}')
          sed -i "s|repository:.*backend.*|repository: ${{ secrets.DOCKERHUB_USERNAME }}/backstage-backend|" helm-chart/values.yaml
          sed -i "s|tag:.*backend.*|tag: $BACKEND_TAG|" helm-chart/values.yaml
          sed -i "s|repository:.*frontend.*|repository: ${{ secrets.DOCKERHUB_USERNAME }}/backstage-frontend|" helm-chart/values.yaml
          sed -i "s|tag:.*frontend.*|tag: $FRONTEND_TAG|" helm-chart/values.yaml

  deploy:
    name: Deploy to ArgoCD
    runs-on: ubuntu-latest
    needs: update-helm-values
    steps:
      - uses: actions/checkout@v4
      - name: Install ArgoCD CLI
        run: |
          sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo chmod +x /usr/local/bin/argocd
      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            ENV="${{ github.event.inputs.environment }}"
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            ENV="prod"
          else
            ENV="dev"
          fi
          echo "env=$ENV" >> $GITHUB_OUTPUT
      - name: ArgoCD Login
        run: |
          argocd login argocd.uday.com.br:9092 --insecure --grpc-web --username admin --password ${{ secrets.ARGOCD_PASSWORD }}
      - name: Sync Apps
        run: |
          for APP in backend frontend; do
            argocd app sync backstage-$APP-${{ steps.env.outputs.env }}
            argocd app wait backstage-$APP-${{ steps.env.outputs.env }} --timeout 300