name: Backstage CI-CD

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'backstage-app/**'
      - 'helm-chart/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'backstage-app/**'
      - 'helm-chart/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Escolha o ambiente para deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  lint-and-validate:
    name: Lint and Validate Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.12.0'

      - name: Lint Helm Chart
        run: helm lint helm-chart/

      - name: Validate Helm Templates
        run: helm template backstage helm-chart/ --debug --dry-run

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: lint-and-validate
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'helm-chart/'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  deploy:
    name: Deploy to ArgoCD
    runs-on: ubuntu-latest
    needs: [lint-and-validate, security-scan]
    steps:
      - uses: actions/checkout@v4

      - name: Determine Deployment Environment
        id: env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            ENV="${{ github.event.inputs.environment }}"
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            ENV="prod"
          else
            ENV="dev"
          fi
          APP_NAME="backstage-$ENV"
          echo "env=$ENV" >> $GITHUB_OUTPUT
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
          echo "Deploying to environment $ENV (App: $APP_NAME)"

      - name: ArgoCD Login
        run: |
          argocd login argocd.uday.com.br:9092 \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}

      - name: Sync Backstage
        run: |
          argocd app sync ${{ steps.env.outputs.app_name }}
          argocd app wait ${{ steps.env.outputs.app_name }} --timeout 300

  notify:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always()
    steps:
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#deployments'
          text: |
            Backstage deployment status: ${{ job.status }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Environment: ${{ steps.env.outputs.env }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}