name: Backstage CI-CD Ultra-Paralelo Matrix

permissions:
  contents: read
  security-events: write

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'backstage-app/**'
      - 'packages/**'
      - 'helm-chart/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'backstage-app/**'
      - 'packages/**'
      - 'helm-chart/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Escolha o ambiente para deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.12.0'
      - name: Lint Helm Chart
        run: helm lint helm-chart/
      - name: Validate Helm Templates
        run: helm template backstage helm-chart/ --debug --dry-run

  security-scan:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'helm-chart/'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  build-and-push:
    name: Build & Push Apps
    runs-on: ubuntu-latest
    needs: security-scan
    strategy:
      matrix:
        app: 
          - backend
          - frontend
    timeout-minutes: 60
    outputs:
      image_tag_backend: ${{ steps.set-tag.outputs.tag }}
      image_tag_frontend: ${{ steps.set-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Set package variables
        run: |
          if [ "${{ matrix.app }}" == "backend" ]; then
            export APP_DIR="./packages/backend"
            export DOCKER_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/backstage-backend"
          else
            export APP_DIR="./packages/app"
            export DOCKER_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/backstage-frontend"
          fi
          echo "APP_DIR=$APP_DIR" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=$DOCKER_IMAGE" >> $GITHUB_ENV

      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/yarn
            ~/.yarn
          key: ${{ format('yarn-cache-{0}-{1}', matrix.app, hashFiles(env.APP_DIR + '/yarn.lock')) }}

      - name: Install dependencies & build
        working-directory: ${{ env.APP_DIR }}
        run: |
          yarn install
          if [ "${{ matrix.app }}" == "backend" ]; then
            yarn tsc
            yarn build
          else
            yarn build
          fi

      - id: set-tag
        run: |
          IMAGE_TAG="v$(echo $GITHUB_SHA | cut -c1-7)"
          echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.APP_DIR }}
          file: ${{ env.APP_DIR }}/Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ steps.set-tag.outputs.tag }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:cache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:cache,mode=max

  update-helm-values:
    name: Update Helm Chart Values
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4
      - name: Update values.yaml with new image tags
        run: |
          sed -i "s|repository:.*backend.*|repository: ${{ secrets.DOCKERHUB_USERNAME }}/backstage-backend|" helm-chart/values.yaml
          sed -i "s|tag:.*backend.*|tag: v$(echo $GITHUB_SHA | cut -c1-7)|" helm-chart/values.yaml
          sed -i "s|repository:.*frontend.*|repository: ${{ secrets.DOCKERHUB_USERNAME }}/backstage-frontend|" helm-chart/values.yaml
          sed -i "s|tag:.*frontend.*|tag: v$(echo $GITHUB_SHA | cut -c1-7)|" helm-chart/values.yaml

  deploy:
    name: Deploy to ArgoCD
    runs-on: ubuntu-latest
    needs: [lint, security-scan, update-helm-values]
    steps:
      - uses: actions/checkout@v4
      - name: Install ArgoCD CLI
        run: |
          sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo chmod +x /usr/local/bin/argocd
      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            ENV="${{ github.event.inputs.environment }}"
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            ENV="prod"
          else
            ENV="dev"
          fi
          echo "env=$ENV" >> $GITHUB_OUTPUT
      - name: ArgoCD Login
        run: |
          argocd login argocd.uday.com.br:9092 --insecure --grpc-web --username admin --password ${{ secrets.ARGOCD_PASSWORD }}
      - name: Sync Apps
        run: |
          for APP in backend frontend; do
            argocd app sync backstage-$APP-${{ steps.env.outputs.env }}
            argocd app wait backstage-$APP-${{ steps.env.outputs.env }} --timeout 300